/*
 * Unannotated Echo
 *
 * Unannotated Echo Service Similar to echo_service.proto but without annotations. See unannotated_echo_service.yaml for the equivalent of the annotations in gRPC API configuration format.  Echo Service API consists of a single service which returns a message.
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package unannotatedecho

// A simple message with many types
type ExamplepbUnannotatedSimpleMessage struct {
	// Id represents the message identifier.
	Id string `json:"id"`
	// Int value field
	Num        string                             `json:"num"`
	Duration   string                             `json:"duration"`
	LineNum    string                             `json:"lineNum"`
	Lang       string                             `json:"lang"`
	Status     *ExamplepbUnannotatedEmbedded      `json:"status"`
	En         string                             `json:"en"`
	No         *ExamplepbUnannotatedEmbedded      `json:"no"`
	ResourceId string                             `json:"resourceId"`
	NId        *ExamplepbUnannotatedNestedMessage `json:"nId"`
}
