/*
 * A Bit of Everything
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package abe

type ExamplepbABitOfEverythingRepeated struct {
	PathRepeatedFloatValue    []float32              `json:"pathRepeatedFloatValue"`
	PathRepeatedDoubleValue   []float64              `json:"pathRepeatedDoubleValue"`
	PathRepeatedInt64Value    []string               `json:"pathRepeatedInt64Value"`
	PathRepeatedUint64Value   []string               `json:"pathRepeatedUint64Value"`
	PathRepeatedInt32Value    []int32                `json:"pathRepeatedInt32Value"`
	PathRepeatedFixed64Value  []string               `json:"pathRepeatedFixed64Value"`
	PathRepeatedFixed32Value  []int64                `json:"pathRepeatedFixed32Value"`
	PathRepeatedBoolValue     []bool                 `json:"pathRepeatedBoolValue"`
	PathRepeatedStringValue   []string               `json:"pathRepeatedStringValue"`
	PathRepeatedBytesValue    []string               `json:"pathRepeatedBytesValue"`
	PathRepeatedUint32Value   []int64                `json:"pathRepeatedUint32Value"`
	PathRepeatedEnumValue     []ExamplepbNumericEnum `json:"pathRepeatedEnumValue"`
	PathRepeatedSfixed32Value []int32                `json:"pathRepeatedSfixed32Value"`
	PathRepeatedSfixed64Value []string               `json:"pathRepeatedSfixed64Value"`
	PathRepeatedSint32Value   []int32                `json:"pathRepeatedSint32Value"`
	PathRepeatedSint64Value   []string               `json:"pathRepeatedSint64Value"`
}
